### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by Matsuri247** [fkmajiji/Unsupervised-Spectral-Demosaicing#2]
i've downloaded the datasets according to the README and run the training code "main_USD_opttrain_optsetup.py" with NTIRE dataset, but i get this message:
RuntimeError: CUDA out of memory. Tried to allocate 900.00 MiB (GPU 0; 23.68 GiB total capacity; 20.04 GiB already allocated; 340.75 MiB free; 21.86 GiB reserved in total by PyTorch)
The batch size is 16. And i also try 12 and 10 but it is still out of memory. I feel quite strange that one RTX 2080Ti with 11GB is enough for the training as you mentioned in your paper, while my device with larger GPU memory fails.
Would you please provide the detailed arg_parser arguments when you conduct the training code on the three datasets?  This is mine on the NTIRE dataset: --cuda --msfa_size 4 --dataset NTIRE --model LSA --train_type EItrain. But i'm not sure whether it is the same as your settings.

**Comment by fkmajiji** [comment]
hello, the batch size in this paper is set to '1', because there is an upsampling operation in the transforming stage, Therefore, the GPU usage will be very high and a larger batch size cannot be set. And, I updated one setup '1_opt.csv'file in "checkpoint\NTIRE_LSA_4_EItrain_Transrandom_with_newPtShift_230811_211045_paperuse", you can check the detailed training setup.

**Comment by Matsuri247** [comment]
Thank you for your reply! And what are the tran_type of 'randomnew_upd3' and 'random_with_newPtShift'? They do not appear in the training code

**Comment by fkmajiji** [comment]
These tran_type names are all 'EItrain' in the public code.
